### PR TITLE
Dockerize hoodie-app-tracker

### PR DESCRIPTION
**Pull request by christophwitzko**
This PR adds Docker support for `hoodie-app-tracker`. :whale:

If code gets pushed to the `master` branch a new Docker image will be built and pushed to [Docker Hub](https://hub.docker.com/r/hoodiehq/hoodie-app-tracker/).

## Deployment
If the image was successfully pushed to [Docker Hub](https://hub.docker.com/r/hoodiehq/hoodie-app-tracker/) a [Docker Hub webhook](https://docs.docker.com/docker-hub/webhooks/) triggers the deployment process. On the server runs a [webhook receiver](https://github.com/christophwitzko/docker-hub-webhook), which pulls the updated image and restarts the container. More info [here](https://github.com/hoodiehq/hoodie-app-tracker/blob/dockerize-app/README.md#continuous-deployment-with-docker-hub).

### CODE REVIEW

**Comment by gr2m** [comment]
Can we move the information on deployment to a separate `deployment.md` file? I’d like to keep the README as simple as possible, to not overwhelm contributors. But we can link to `deployment.md` from the `README.md` file.

Would that be ok?

**Comment by christophwitzko** [comment]
LGTM :+1:

**Comment by gr2m** [comment]
LGTM :) I’ll rebase and merge it

**Comment by gr2m** [comment]
I only added the Maintainers team to the project, I guess that’s why the LGTM did not work. I’ll merge it anyway because I can #AdminFTW

**Pull request merged**
