### PR TITLE
fix: change highlighted color

### PR DESCRIPTION
**Pull request by jsimplicio**
I tried the green and it actually didn't look too contrasty when the font wasn't bold. So I am using a decent shade of blue now. Let me know if it looks good!

I used this tool: http://leaverou.github.io/contrast-ratio/#%23436EEE-on-white

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM :+1: 

I’m not sure if the hover of the buttons in the account page is good enough for color blind people, maybe we can change something else than just the color? But I’d suggest we address this in a follow up issue

**Comment by nickcolley** [comment]
You're going to hate me but this doesn't hit the mark for contrast in places :(

Worth checking with https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en

You can right click a link -> Inspect element -> Accessibility properties (next to style pane) and it'll show you the contrast based on the font-size and fore/background colour

Doing this I noticed the navigation links are lower.than level AA, not by much but if we're going to change the colour from something that passes level AAA I guess that's a regression.

Maybe the fix here is just to improve the nav menu buttons so they don't rely on the colour border change?

**Comment by gr2m** [comment]
maybe we should remove colors altogether and only use black / white / grey shades :D

**Comment by jsimplicio** [comment]
Agh I don't use Chrome. Can you do the test and see if this shade of gray is good contrast enough? Please :) @nickcolley

**Comment by gr2m** [comment]
@jsimplicio Just remembered: Mac has greyscale built in

screen shot 2016-03-13 at 12 40 04

**Comment by jsimplicio** [comment]
Alright, apparently `blue` is really high contrast against white at all sizes AAA.
I bumped the font from `16px` to `18px` to make it even more readable.
I also underlined all links, except for the navigation ones.

How's this?

screen shot 2016-03-13 at 12 05 14 pm
screen shot 2016-03-13 at 12 05 20 pm

**Comment by gr2m** [comment]
I say let’s :shipit: and keep iterating if there are still things we can improve :)

**Comment by nickcolley** [comment]
LGTM :+1:

**Comment by nickcolley** [comment]
:+1: only tiny nit I can think of is the favicon is purple atm

**Pull request merged**
