### PR TITLE
Fixing button height next to inputs. Remove a p tag

### PR DESCRIPTION
**Pull request by jsimplicio**
Small fixes I wanted to take care of. Making buttons same height as inputs.
Making some inputs taller inside user settings.

### CODE REVIEW

**Comment by nickcolley** [comment]
We wouldn't have these consistencies if we were using classes, just saying ;)

**Comment by jsimplicio** [comment]
Should we make a class for the inputs and buttons?

**Comment by nickcolley** [comment]
Yeah that's how it was previously

https://github.com/hoodiehq/hoodie-app-tracker/commit/24c070bc5b6758908c31421a981d403a4011c0b5#diff-4c1a8d47b28694c10a33098fd383773bR81

**Comment by jsimplicio** [comment]
So should I make a class for input and button so they have same padding and stuffs?

**Comment by nickcolley** [comment]
:+1: Thanks Julia

**Pull request merged**
