### PR TITLE
Bluemix deployment

### PR DESCRIPTION
**Pull request by mmcelaney**
Followed the twelve-factor app checklist for deploying an app to IBM Bluemix.

### CODE REVIEW

**Comment by gr2m** [comment]
Instead of creating the `.cfignore`, `Procfile` and `manifest.yml`, can you add it to the deployment documentation? I also wonder if we need the `.cfignore` file and the `Procfile` at all? I could not try it myself yet, maybe tomorrow

**Comment by gr2m** [comment]
deployment to bluemix works now, both via command line and the button. Before merging, we need to set the button to show to our main repository (it currently points to @mmcelaney’s fork). ping @hoodiehq/maintainers for review

**Comment by gr2m** [comment]
@mmcelaney woop we just had another review with @janl and are going to merge it. You go down in history for the coolest first-time Open Source pull request that I’ve ever seen :)

If you like, you could also write a blog post about it so we can promote this some more?

**Comment by janl** [comment]
+1 this is cool

**Comment by mmcelaney** [comment]
Yay thanks @gr2m and @janl!!! At your request I'm going to write a blog post and I'll let you know when it's ready to spread around. :)

**Comment by gr2m** [comment]
folks love short screencasts among blog posts, if you are fancy too make one :)

**Comment by mmcelaney** [comment]
Hm... do you have an example of such a thing?

**Comment by gr2m** [comment]
here: http://hood.ie/blog/single-line-deployment.html

But really don’t worry about it, it was just an idea :) No need for a video, this is awesome by itself

**Pull request merged**
