### PR TITLE
fix: add favicon

### LINKED ISSUE #30: add favicon.ico
At least chrome currently logs errors in the console like this:

screen shot 2016-03-05 at 14 31 40

Simplest would be to use a [transparent favicon.ico](http://transparent-favicon.info/favicon.ico) until someone wants to make a custom one :)

### PR DESCRIPTION
**Pull request by nickcolley**
Drew a little list icon up, nothing fancy, maybe we could get this in and if someone else has something we can replace it?

image

---

fixes #30

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM :+1:

**Comment by jsimplicio** [comment]
This is perfect :+1:

**Comment by gr2m** [comment]
@jsimplicio could you merge this? I can help of course. You will need to rebase first, the commands will look something like this

```bash
# fetch all latest changes from remote
git fetch
git checkout master
git pull origin master
# checkout Nick’s branch
git checkout 30-add-favicon
git rebase master
# merge
git checkout master
git merge 30-add-favicon
# push
git push origin master
# delete remote branch
git push origin :30-add-favicon
# delete local branch
git branch -d 30-add-favicon
```

**Comment by nickcolley** [comment]
f2b9794b669a5

**Pull request closed without merging**
